### ISSUE TITLE
Calling plist_options is deprecated

### ISSUE THREAD

**Issue by tybritten** [stripe/homebrew-stripe-mock#7]
Homebrew now warns on installing stripe-mock:
```Warning: Calling plist_options is deprecated! Use service.require_root instead.```

**Comment by thinkverse** [comment]
Issue persists even after #8 was merged, seems the `stripe-ci` overwrote the PR in https://github.com/stripe/homebrew-stripe-mock/commit/fd81b7ace44881eb5941b24cc6bb04df052fc43a, @pakrym-stripe or @richardm-stripe might wanna look into that. 👍

**Comment by tybritten** [comment]
ahh I figured out what happened, the goreleaser is where this needs to be updated: https://github.com/stripe/stripe-mock/blob/master/goreleaser.yml#L30-L69

**Comment by tybritten** [comment]
the block in goreleaser should be:
```
brews:
  - tap:
      owner: stripe
      name: homebrew-stripe-mock
    homepage: "https://github.com/stripe/stripe-mock"
    description: "stripe-mock is a mock HTTP server that responds like the real Stripe API. It can be used instead of Stripe's testmode to make test suites integrating with Stripe faster and less brittle."
    commit_author:
      name: stripe-ci
      email: support@stripe.com
    service: |
        keep_alive successful_exit: false
        run [
          opt_bin/"stripe-mock",
          "-http-port", 
          "12111",
          "-https-port",
          "12112"
        ]
        working_dir var
        log_path var/"log/stripe-mock.log"
        error_log_path var/"log/stripe-mock.log"

**Comment by thinkverse** [comment]
Fix has been implemented https://github.com/stripe/stripe-mock/pull/399, warning no longer displays after updating to v0.158.0. 👍
